version: '3.9'
services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  api:
    build: ./backend
    environment:
      MONGODB_URI: mongodb://mongo:27017/linksnap
      PORT: 5000
      BASE_URL: http://localhost:5000
      FRONTEND_ORIGIN: http://localhost:5173,http://localhost:8080
    depends_on:
      - mongo
    ports:
      - "5000:5000"
  web:
    build: ./frontend
    environment:
      VITE_API_BASE_URL: http://localhost:5000
    depends_on:
      - api
    ports:
      - "8080:80"
volumes:
  mongo_data:
